### PR TITLE
Added loader while data is fetched

### PR DESCRIPTION
**Pull request by pavan-choudhary**
Loader will apper on data fetch and on manually searching city. #116

### CODE REVIEW

**Comment by avinash201199** [comment]
please add the screenshot of the ui change or loader

**Comment by pavan-choudhary** [comment]
> please add the screenshot of the ui change or loader

Screenshot 2022-10-10 at 9 42 09 AM

**Comment by avinash201199** [comment]
please resolve conflicts

**Comment by avinash201199** [comment]
data is fetched in very less time so no need to add loader it will increase the time

**Comment by pavan-choudhary** [comment]
> data is fetched in very less time so no need to add loader it will increase the time

Screenshot 2022-10-10 at 7 56 06 PM

less time for fast internet, since loader is pure CSS no extra time is required.
For conflicts: they happened after my PR.

**Pull request closed without merging**
