### PR TITLE
Added location based infos

### PR DESCRIPTION
**Pull request by decaffeinatedcoffee**
Uses the browser location feature to detect user location to show data.

### CODE REVIEW

**Comment by avinash201199** [comment]
it's already location based

**Comment by decaffeinatedcoffee** [comment]
> it's already location based

not automatically since it showed Delhi while i live in Brazil

**Comment by avinash201199** [comment]
> > it's already location based
> 
> not automatically since it showed Delhi while i live in Brazil

okay

**Comment by avinash201199** [comment]
thank you for your contribution :)

**Comment by avinash201199** [comment]
hey there is some issue in UI structure and also background image is not loading 

image
image


can you please check and edit it

**Comment by decaffeinatedcoffee** [comment]
> hey there is some issue in UI structure and also background image is not loading
> 
> image image
> 
> can you please check and edit it

oh ye

**Comment by decaffeinatedcoffee** [comment]
hm, the image is loading for me, and also the UI looks good.
image

**Comment by avinash201199** [comment]
> hm, the image is loading for me, and also the UI looks good. image

because I editd the , thank you for your contribution :)

**Comment by decaffeinatedcoffee** [comment]
> > hm, the image is loading for me, and also the UI looks good. image
> 
> because I editd the , thank you for your contribution :)

Actually i was using the same code i uploaded to test

**Comment by avinash201199** [comment]
You can also contribute by designing the webiste for this repo- https://github.com/avinash201199/Paid-Internship-List

**Pull request merged**
