### PR TITLE
Temp Unit Button and links in footer

### PR DESCRIPTION
**Pull request by UtsavMehta1902**
Improved the styling of Temperature Unit Converter Button and the icons in footer, both in responsive mode.

### CODE REVIEW

**Comment by avinash201199** [comment]
resolve conflicts and add ss

**Comment by UtsavMehta1902** [comment]
@avinash201199 I resolved the merge conflicts, and this is how the website looks in responsive mode - 
image
Please merge this PR and give hacktoberfest tag.
Thank You

**Comment by avinash201199** [comment]
good work , can you please resolve the conflicts again

**Comment by UtsavMehta1902** [comment]
Removed the merge conflicts, website works just as expected.

**Pull request merged**
