### PR TITLE
added mouse follower 

### PR DESCRIPTION
**Pull request by mangal2003**

### CODE REVIEW

**Comment by avinash201199** [comment]
please add ss or demo video of ui changes

**Comment by mangal2003** [comment]
added demo video of mouse follower UI

**Comment by avinash201199** [comment]
sorry brother if you miss understoond , you have to add ss or demo video here so that I can review the ui changes been done by you

**Comment by avinash201199** [comment]
image
just drag and drop the demo video recorded or ss in this write container it will be automatically uploaded

**Comment by mangal2003** [comment]
https://github.com/avinash201199/weather-app/assets/142136696/2a34bf50-d55c-47f1-8e58-31d9e6389736

**Comment by avinash201199** [comment]
Thank you for your valuable contribution :)

**Comment by mangal2003** [comment]
It feels great to contribute in projects when you learn with contribution. Can I create new pull request in the same repository for my projects in C language (console based).

**Comment by avinash201199** [comment]
> It feels great to contribute in projects when you learn with contribution. Can I create new pull request in the same repository for my projects in C language (console based).

you can contribute to more repo- 
1- https://github.com/avinash201199/weather-app
2- https://github.com/avinash201199/stopwatch
3- https://github.com/avinash201199/To-Do-List
4- https://github.com/avinash201199/My-Gallery-4u
5- https://github.com/avinash201199/Free-courses-with-Certificates

**Pull request merged**
