### PR TITLE
I Have changed background animations , I think I can contribute more in this (PLEASE APPROVE IT FOR HACKTOBERFEST )

### PR DESCRIPTION
**Pull request by sourabh1428**
Thanks!

### CODE REVIEW

**Comment by avinash201199** [comment]
please resolve conflicts and add screenshot of the changes

**Review by sourabh1428 — COMMENTED** [review]
https://user-images.githubusercontent.com/63462210/194031010-d9555ea7-22d3-4370-b7c4-8445e3d98b00.mp4

**Comment by avinash201199** [comment]
resolve branch conflict

**Comment by sourabh1428** [comment]
done

**Comment by avinash201199** [comment]
image
 
bug in the code

**Pull request closed without merging**
