### PR TITLE
Update script.js

### PR DESCRIPTION
**Pull request by ibbatta**
Used template string for a better string concat

### CODE REVIEW

**Comment by avinash201199** [comment]
please add the screenshot of the change

**Comment by ibbatta** [comment]
You can see it in [FILE CHANGES](https://github.com/avinash201199/weather-app/pull/40/files) path, anyway: 
image

**Comment by avinash201199** [comment]
I was talking about the effect on frontend

**Comment by ibbatta** [comment]
@avinash201199 well, absolutely nothing will change.
It's just another (more reliable and clean) way to write string concatenation

**Comment by avinash201199** [comment]
Thank you for your contribution :)

**Pull request merged**
