### PR TITLE
Fixed Merge Conflict

### PR DESCRIPTION
**Pull request by Adithya-K-Shetty**

### CODE REVIEW

**Comment by avinash201199** [comment]
which conflict you are resolving ?

**Comment by Adithya-K-Shetty** [comment]
Hello Sir
Earlier i had generated a PR and u told  me to delete the repo and to fork it again  to resolve the conflict and i did that

**Comment by avinash201199** [comment]
okay , please resolve again , or you can work on new issue

**Comment by Adithya-K-Shetty** [comment]
Okay sir
sir i created a new issue

**Pull request closed without merging**
