### PR TITLE
Description:

### PR DESCRIPTION
**Pull request by Mirthhh08**
- Applied a linear gradient background to the Weather App in header component , weather card and forcast component items  to enhance its visual appeal.

Changes Made:
- Added gradient background to the app for a more engaging look.

### ➕ Changes Introduced

-Added gradient background to the app for a more engaging look.

- Applied a linear gradient background to the Weather App in header component , weather card and forcast component items  to enhance its visual appeal.

### 📷 Screenshots

image

### CODE REVIEW

**Comment by Mirthhh08** [comment]
this is my first pull request i hope you will like the gradient look of the weather app.

**Comment by avinash201199** [comment]
Please resolve the branch conflict , try to fork and copy paste the changes !

**Comment by Mirthhh08** [comment]
I have resolved the conflicts

**Comment by avinash201199** [comment]
thank you for your contribution :)

**Pull request merged**
