### PR TITLE
Week based weather update

### PR DESCRIPTION
**Pull request by Suraj-Bhandarkar-S**
#1 Added API call to display day based weather for the city in focus 
Html and CSS file modified for styling purpose
Added Moment.js for extension purpose

If any questions or changes needed let me know 

Daily weather updates

### CODE REVIEW

**Comment by avinash201199** [comment]
image

A little improvement , can you please remove the overlapping

**Comment by Suraj-Bhandarkar-S** [comment]
> image
> 
> A little improvement , can you please remove the overlapping

Oh, Yes okay will work on it

**Comment by Suraj-Bhandarkar-S** [comment]
weather
Can you check now please I have added the new changes

**Comment by avinash201199** [comment]
> weather Can you check now please I have added the new changes

yeah it's good , you can also add date with day in week section

**Comment by Suraj-Bhandarkar-S** [comment]
Hi Avinash,
I see you have merged but getting this do you have any idea? on this
image

**Comment by avinash201199** [comment]
may be it will take some time to refelect

**Comment by avinash201199** [comment]
> may be it will take some time to refelect



> may be it will take some time to refelect , last year it was one day may be.

also they will review the pr and last year they have taken 14 days for approving

**Pull request merged**
