### PR TITLE
Added Notifications

### PR DESCRIPTION
**Pull request by Pavan-Rajesh**

### CODE REVIEW

**Comment by avinash201199** [comment]
please screenshot and resolve conflicts

**Comment by Pavan-Rajesh** [comment]
Screenshot (22)

**Comment by Pavan-Rajesh** [comment]
Screenshot (24)
Screenshot (23)

**Comment by avinash201199** [comment]
which type of notification it will show

**Comment by Pavan-Rajesh** [comment]
just i added the notification hi welcome to weather app

but if we want by clicking on that notification we can go to a new window and  but I didnt do it

for more reference checkout this

https://www.javascripttutorial.net/web-apis/javascript-notification/

if  you want when you click on new window you can see the hourly forecast of the weather in that new page but i didnt develop it

**Comment by avinash201199** [comment]
image

bug in your code , reverting the change

**Pull request merged**
