### PR TITLE
Improved UI of Heading and Footer

### PR DESCRIPTION
**Pull request by SAIF0556**
Issue Number :-#142

Header Before
header_before

Header After
header_after1

footer before
footer_before
footer after
footer_final

### CODE REVIEW

**Comment by avinash201199** [comment]
good work , please resolve conflicts

**Comment by SAIF0556** [comment]
Sure sir.

**Comment by avinash201199** [comment]
please delete the repo and fork again to do your changes :)

**Comment by SAIF0556** [comment]
Ok sir

**Pull request closed without merging**
