### PR TITLE
Unit conversion feature added and hide the scrollbar for better UI

### PR DESCRIPTION
**Pull request by helloArnab**
1. Added a unit conversion toggler which will convert celcius into farenheit and vice versa.
2. Hide scrollbar but keep functionality for better UI

Screenshot (107)
Screenshot (108)
Screenshot (106)

### CODE REVIEW

**Comment by helloArnab** [comment]
Before  the change : 
<br>
Screenshot (109)

<br>
<br>
<br>


After the change:
 <br>
Screenshot (112)

Screenshot (113)

**Comment by helloArnab** [comment]
I hope you find this feature useful and hope u accept my pr :)

**Comment by avinash201199** [comment]
resolve conflicts

**Comment by avinash201199** [comment]
the feature is very useful :)

**Comment by helloArnab** [comment]
I have resolved the conflict

**Comment by avinash201199** [comment]
image

some bug in your code , can't switch between units

**Comment by helloArnab** [comment]
But in the website it is fine.

**Pull request merged**
