### PR TITLE
Adithya K Shetty

### LINKED ISSUE #222: Updating the footer (Social Media Icons)
Using font awesome icons

### PR DESCRIPTION
**Pull request by Adithya-K-Shetty**
### 🛠️ Fixes Issue

 Closes #222

### ➕ Changes Introduced

html & css changes 
also added a fontawesome CDN

## Changes Other Than The Issue
added  a scroll bar

### CODE REVIEW

**Comment by avinash201199** [comment]
Please add the screenshot of the changes or a video demo

**Comment by Adithya-K-Shetty** [comment]
image

**Comment by avinash201199** [comment]
Thank you for your contribution :)

**Comment by Adithya-K-Shetty** [comment]
Welcome 🙏

**Pull request merged**
