### PR TITLE
Weather app config current day - Make current day obvious

### LINKED ISSUE #108: Improve user Xperience  - Make current day more visible
In the present UI, the weather forecast of the days of the week is shown, but the user can hardly tell which day it is without really taking a limb/guess or really focusing and observing each day, especially if the day occurs twice.
Take for instance the picture below:
Screenshot (257)
this contains 2(TWO) Saturdays with different weather forecasts, Imagine being on a Saturday and not knowing which Saturday forecast is which, it will be pertinent or important to resolve this issue as it will boost the user's experience.

### PR DESCRIPTION
**Pull request by Zeuhz-Droid**
Closes #108 

Done - created a function to make the *current day* stand out.
Screenshot (258)
As seen in the image above, when you search "Canada" as your country, Sunday, which is today's day, appears first when and is given a different styling from others,
This is different when you search "Tokyo" as your country or state, Sunday appears in a different position and stands out as well, this is shown below.
Screenshot (260)

### CODE REVIEW

**Comment by avinash201199** [comment]
please resolve conflicts

**Comment by Zeuhz-Droid** [comment]
Done, conflicts resolved.

**Comment by avinash201199** [comment]
hey please delete the repo and then fork the repo to do your changes to avoid conflicts or creation of new branch

**Comment by avinash201199** [comment]
Sorry for closing , I hope you will understand , please make pr again

**Comment by Zeuhz-Droid** [comment]
No problem, I will do that. Thank you

**Pull request closed without merging**
